### ISSUE TITLE
4G signal significantly weaker than on unmodded firmware

### ISSUE THREAD

**Issue by Ingvix** [Huawei-LTE-routers-mods/Huawei_E5372_mod_fw#2]
Before installing this modded firmware I used to always get 4-5 bars on 4G on my E5372 but now it sometimes reaches 4 at the best times, most of the time stays at 3 but not too rarely might go even lower or rarely even get no signal. Any idea what might be the cause?

I'm not too knowlegded in the field but would it be possible that the frequency bands differ a bit to those used on this firmware? I'm located in Finland and the UI was in Finnish so the firmware might've also designed for use in Finland. I might be completely wrong in this one if the LTE bands are more standardized than I'm assuming. I didn't happen to take note of the stock firmware version but it didn't even have the option to select the frequency bands.

I also wondered about the possibility that the signal strength presented might've been higher than the actual strenght if there was such a scheme behind it to keep customers happy. But this doesn't really line up with the fact that the data trasfer rates seems to be generally lower and more unstable than before. I just installed the firmware yesterday so I need to test it a bit more to be sure.

EDIT: Also the modem is been positioned in the exact same spot so that shouldn't be a factor here.

**Comment by ValdikSS** [comment]
The signal _bar_ is different on different firmware versions. You should compare the signal characteristics, such as RSSQ and SINR. Also, as you said, the level difference could be due to different frequency/cell. In modded firmware you could change the frequency.

**Comment by Ingvix** [comment]
I tested all the bands separately, in groups and with all selected as well before but didn't get similar results to unmodded firmwares signal. What I meant that the bands would use slightly different frequency ranges on this firmware but I guess that might not be the case.

Now though the connection seems to be holding pretty well with 4 bars compared to last night when at one point at got no signal even with all band enabled. Might've been just the time I did the testing or something else. If it stays as strong as it is now, there might not be an issue after all.

I probably should've looked at those characteristics before installing this firmware to test it reliably. Though I'm not sure how would I get them on the stock firmware but it doesn't matter now. I consider this matter closed for now and come back if something still seems off.

**Comment by Ingvix** [comment]
Btw, is there a way to check the RSSQ and SINR values on the firmware through telnet or otherwise?

**Comment by ValdikSS** [comment]
AFAIR /dev/appvcom port reports signal every several seconds.

```
^HCSQ:"LTE",x,y,z,t , where
x - RSSI
RSSI = (x - 121) dBm;

y - RSRP:
RSRP = (y - 141) dBm;

z - SINR:
z=0 => SINR < -20 dB;
z=1...250 => SINR = ((z-1)/5 - 20) dB;
z=251 => SINR >= 30 dB;

t - RSRQ:
RSRQ = (t/2 - 20) dB.
```

**Comment by Ingvix** [comment]
Thanks, that's great.
