### ISSUE TITLE
E5372Ts-32 Extended menu display & ovpn option.

### ISSUE THREAD

**Issue by vdhub** [Huawei-LTE-routers-mods/Huawei_E5372_mod_fw#5]
Hi
I just upgraded my router. I have a Huawei E5372T ; E5372-612B ; and in the bottom of the label it says E5372Ts-32

Is there a way to enable the oled extended menu ? 
In the same time I see that there is support for wireguard and openvpn. How can I set those ? as it seems that I cannot doit in the Interface nor in the oled display and I don't have any way of connecting to the router via telnet I guess or ssh.

**Comment by ValdikSS** [comment]
>Is there a way to enable the oled extended menu ?

Read the readme.

>In the same time I see that there is support for wireguard and openvpn.

No Wireguard support.

Issue section is for project issues. Please refrain from posting questions here.
