### ISSUE TITLE
v2ray

### ISSUE THREAD

**Issue by chelaxian** [Huawei-LTE-routers-mods/Huawei_E5372_mod_fw#6]
hello! how about to add v2ray client to this router? would be very nice

**Comment by ValdikSS** [comment]
You can install any software included in entware with `entware` command.
v2ray has RAM requirements incompatible with Huawei LTE routers, at least of the older generations.

**Comment by chelaxian** [comment]
how much v2ray client need? this router as i can see via telnet has 32 Mb RAM. but in specs on 4pda it should has 128 Mb.
is 128 Mb RAM compatible with v2ray?

**Comment by ValdikSS** [comment]
There's somewhere about 17 MB free RAM on E5372, while v2ray needs at least 30-35 or so.
